### ISSUE TITLE
[module/spotify-track],  there isn't any spotify.py 

### ISSUE THREAD

**Issue by Gamero-hub** [Spaxly/dotfiles#1]
Can u share the spotify.py script at $HOME/.config/bspwm/apps/polybar/scripts/spotify.py i can't use the polybar module without the script

**Comment by ohxxm** [comment]
I actually don't use this script anymore as it only works for Spotify so I implemented a new script in shell that allows for all players to work including YouTube, Spotify, etc. That script is located in the scripts directory. The module for this is called player-title but will be changed to just player in the next commit. As for the spotify.py script, I highly recommend you use the new script as its much more efficient and faster.
