### ISSUE TITLE
error at modules.ini polybar

### ISSUE THREAD

**Issue by Gamero-hub** [Spaxly/dotfiles#2]
Sorry for open another issue but, In ~/.config/bspwm/polybar/modules/modules.ini at the line 565-571: 
[module/powermenu]
type = custom/text
content = ""
content-font = 2
content-background = ${colors.surface0}
content-foreground = ${colors.red}
click-left = $HOME/.config/bspwm/apps/rofi/bin/powermenu <--- this ins't in that directory, there is at  $HOME/.config/bspwm/apps/rofi/powermenu

**Comment by ohxxm** [comment]
Fixed this, thanks for notifying me. I don't use some of these modules so I didn't update them but this will be fixed in the next commit.
